import Head from 'next/head'
import About from '../components/About';
import Header from '../components/Header'
import Hero from '../components/Hero';
import Project from "../components/project";
import Contact from "../components/contact";


export default function Home() {
  return (
		<div className="h-screen bg-[rgb(36,36,36)] overflow-y-scroll text-white snap-y overflow-x-hidden ">
			<Head>
				<title>Kangqiang Yang Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<section id="hero" className="snap-start">
				<Hero />
			</section>

			<section id="about" className="snap-center">
				<About />
			</section>

			<section id="project" className="snap-start">
				<Project />
			</section>

			<section id="contact" className="snap-center">
				<Contact />
			</section>
		</div>
	);
}
