import Head from 'next/head'
import About from '../components/About';
import Header from '../components/Header'
import Hero from '../components/Hero';
import Project from "../components/project";
import Contact from "../components/contact";
import Link from 'next/link';
import { ArrowUpIcon } from '@heroicons/react/24/solid';


export default function Home() {
  return (
		<div className="h-screen bg-[rgb(36,36,36)] overflow-y-scroll text-white snap-y overflow-x-hidden scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#f7ab0a]/80">
			<Head>
				<title>Kangqiang Yang Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<section id="hero">
				<Hero />
			</section>

			<section id="about" className="snap-center">
				<About />
			</section>

			<section id="project" className="snap-start">
				<Project />
			</section>

			<section id="contact">
				<Contact />
			</section>

			<section className='sticky bottom-5 ml-10'>
				<Link href="#hero">
	
					<ArrowUpIcon className="h-7 border cursor-pointer rounded-full bg-slate-800 text-white" />
	
				</Link>
			</section>
		</div>
	);
}
